using Domain.Enums;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Persistence.Data.DefaultData
{
    /// <summary>
    /// Per-role default permission sets, expressed purely as <see cref="Permission"/>
    /// enum lists.
    ///
    /// IMPORTANT: do not embed role IDs here. The previous version baked
    /// <c>DefaultUserRole.Instance[i].Id</c> into pre-built UserRolePermission rows;
    /// because <c>Instance[i].Id</c> is regenerated by <c>Guid.NewGuid()</c> on
    /// every process start, those rows pointed at GUIDs that did not exist in
    /// already-seeded databases, which crashed startup with a foreign-key
    /// violation (FK_UserRolePermissions_UserRoles_UserRoleId). The seeder now
    /// resolves real role IDs from the database at runtime and pairs them with
    /// these enum lists.
    /// </summary>
    public sealed class DefaultUserRolePermissions
    {
        public static IReadOnlyList<Permission> AdminPermissions { get; } =
            Enum.GetValues<Permission>().ToList();

        /// <summary>
        /// Family / Member / File CRUD. User / Role / RolePermission management is admin-only.
        /// </summary>
        public static IReadOnlyList<Permission> NewUserPermissions { get; } = new[]
        {
            Permission.GET_FAMILY, Permission.CREATE_FAMILY, Permission.UPDATE_FAMILY, Permission.DELETE_FAMILY,
            Permission.GET_MEMBER, Permission.CREATE_MEMBER, Permission.UPDATE_MEMBER, Permission.DELETE_MEMBER,
            Permission.GET_FILE,   Permission.CREATE_FILE,   Permission.UPDATE_FILE,   Permission.DELETE_FILE
        };

        private DefaultUserRolePermissions() { }
    }
}
